CREATE TABLE edge_user (
 id VARCHAR(128) PRIMARY KEY, status VARCHAR(20) NOT NULL DEFAULT 'ACTIVE', created_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP
);
CREATE TABLE profile (
 user_id VARCHAR(128) PRIMARY KEY REFERENCES edge_user(id) ON DELETE CASCADE,
 display_name VARCHAR(100) NOT NULL DEFAULT 'Student', role_id VARCHAR(60) NOT NULL DEFAULT 'java-developer',
 weekly_goal INTEGER NOT NULL DEFAULT 5 CHECK(weekly_goal BETWEEN 1 AND 30),
 education TEXT NOT NULL DEFAULT '', skills TEXT NOT NULL DEFAULT '[]', timezone VARCHAR(80) NOT NULL DEFAULT 'Asia/Kolkata',
 retention_days INTEGER NOT NULL DEFAULT 7 CHECK(retention_days IN (7,30)), consent_version VARCHAR(20), updated_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP
);
CREATE TABLE role_catalog(id VARCHAR(60) PRIMARY KEY,name VARCHAR(100) NOT NULL,skills TEXT NOT NULL);
CREATE TABLE topic(id VARCHAR(80) PRIMARY KEY,subject VARCHAR(20) NOT NULL,name VARCHAR(100) NOT NULL);
CREATE TABLE question (
 id VARCHAR(36) PRIMARY KEY, family_id VARCHAR(36) NOT NULL, version INTEGER NOT NULL, topic_id VARCHAR(80) NOT NULL REFERENCES topic(id),
 type VARCHAR(20) NOT NULL CHECK(type IN ('MCQ','CODE_OUTPUT','SHORT_ANSWER')),
 difficulty VARCHAR(10) NOT NULL CHECK(difficulty IN ('EASY','MEDIUM','HARD')),
 prompt TEXT NOT NULL, options TEXT NOT NULL, answer TEXT NOT NULL, explanation TEXT NOT NULL,
 criteria TEXT NOT NULL, source TEXT NOT NULL, license VARCHAR(100) NOT NULL, author VARCHAR(128) NOT NULL,
 reviewer VARCHAR(128), state VARCHAR(20) NOT NULL DEFAULT 'DRAFT', created_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
 UNIQUE(family_id,version)
);
CREATE INDEX question_selection ON question(topic_id,difficulty,state);
CREATE TABLE interview_seed(id VARCHAR(80) PRIMARY KEY,role_id VARCHAR(60) NOT NULL,kind VARCHAR(20) NOT NULL,topic VARCHAR(80) NOT NULL,prompt TEXT NOT NULL,reference_answer TEXT NOT NULL,state VARCHAR(20) NOT NULL DEFAULT 'DRAFT',reviewer VARCHAR(128));
CREATE TABLE activity (
 id VARCHAR(36) PRIMARY KEY, user_id VARCHAR(128) NOT NULL REFERENCES edge_user(id) ON DELETE CASCADE,
 module VARCHAR(20) NOT NULL, state VARCHAR(24) NOT NULL, context TEXT NOT NULL,
 report TEXT, score DOUBLE PRECISION, eligible BOOLEAN NOT NULL DEFAULT FALSE, version INTEGER NOT NULL DEFAULT 0,
 created_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP, completed_at TIMESTAMP WITH TIME ZONE,
 submission_key VARCHAR(100) NOT NULL, request_hash VARCHAR(64) NOT NULL,
 UNIQUE(user_id,submission_key)
);
CREATE INDEX activity_history ON activity(user_id,created_at);
CREATE TABLE test_attempt(activity_id VARCHAR(36) PRIMARY KEY REFERENCES activity(id) ON DELETE CASCADE,deadline TIMESTAMP WITH TIME ZONE NOT NULL);
CREATE TABLE test_item(
 id VARCHAR(36) PRIMARY KEY,activity_id VARCHAR(36) NOT NULL REFERENCES test_attempt(activity_id) ON DELETE CASCADE,
 question_id VARCHAR(36) NOT NULL REFERENCES question(id),position INTEGER NOT NULL,
 response TEXT,marked BOOLEAN NOT NULL DEFAULT FALSE,version INTEGER NOT NULL DEFAULT 0,points DOUBLE PRECISION,
 grading_status VARCHAR(20) NOT NULL DEFAULT 'UNANSWERED',feedback TEXT,UNIQUE(activity_id,position)
);
CREATE TABLE interview_session(
 activity_id VARCHAR(36) PRIMARY KEY REFERENCES activity(id) ON DELETE CASCADE, remaining_seconds INTEGER NOT NULL,
 max_questions INTEGER NOT NULL,wall_deadline TIMESTAMP WITH TIME ZONE NOT NULL,current_started TIMESTAMP WITH TIME ZONE,
 current_sequence INTEGER NOT NULL DEFAULT 0
);
CREATE TABLE interview_turn(
 id VARCHAR(36) PRIMARY KEY,activity_id VARCHAR(36) NOT NULL REFERENCES interview_session(activity_id) ON DELETE CASCADE,
 sequence INTEGER NOT NULL,topic VARCHAR(80) NOT NULL,kind VARCHAR(20) NOT NULL,prompt TEXT NOT NULL,reference_answer TEXT NOT NULL,
 followup_depth INTEGER NOT NULL DEFAULT 0,answer TEXT,media_id VARCHAR(36),evaluation TEXT,submission_key VARCHAR(100),
 UNIQUE(activity_id,sequence)
);
CREATE TABLE media(
 id VARCHAR(36) PRIMARY KEY,user_id VARCHAR(128) NOT NULL REFERENCES edge_user(id) ON DELETE CASCADE,
 storage_key VARCHAR(100) NOT NULL UNIQUE,bytes BIGINT NOT NULL,duration_seconds DOUBLE PRECISION NOT NULL,
 checksum VARCHAR(64) NOT NULL,transcript TEXT,state VARCHAR(20) NOT NULL,
 created_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,delete_after TIMESTAMP WITH TIME ZONE NOT NULL,
 UNIQUE(user_id,checksum)
);
CREATE TABLE english_attempt(
 activity_id VARCHAR(36) PRIMARY KEY REFERENCES activity(id) ON DELETE CASCADE,group_id VARCHAR(36) NOT NULL,
 previous_id VARCHAR(36),prompt_version VARCHAR(20) NOT NULL DEFAULT 'intro-v1',
 media_id VARCHAR(36) REFERENCES media(id) ON DELETE SET NULL,raw_transcript TEXT,confirmed_transcript TEXT,edited BOOLEAN NOT NULL DEFAULT FALSE
);
CREATE TABLE job(
 id VARCHAR(36) PRIMARY KEY,user_id VARCHAR(128) REFERENCES edge_user(id) ON DELETE CASCADE,kind VARCHAR(40) NOT NULL,payload TEXT NOT NULL,
 dedupe_key VARCHAR(180) NOT NULL UNIQUE,state VARCHAR(20) NOT NULL DEFAULT 'QUEUED',attempts INTEGER NOT NULL DEFAULT 0,
 available_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,lease_until TIMESTAMP WITH TIME ZONE,error_code VARCHAR(100),
 created_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP
);
CREATE INDEX job_due ON job(state,available_at);
CREATE TABLE assessment_outbox(
 id VARCHAR(36) PRIMARY KEY,activity_id VARCHAR(36) NOT NULL REFERENCES activity(id) ON DELETE CASCADE,
 version INTEGER NOT NULL,payload TEXT NOT NULL,processed BOOLEAN NOT NULL DEFAULT FALSE,UNIQUE(activity_id,version)
);
CREATE TABLE competency_evidence(
 activity_id VARCHAR(36) NOT NULL REFERENCES activity(id) ON DELETE CASCADE,competency VARCHAR(80) NOT NULL,score DOUBLE PRECISION NOT NULL,
 PRIMARY KEY(activity_id,competency)
);
CREATE TABLE progress_snapshot(
 id VARCHAR(36) PRIMARY KEY,user_id VARCHAR(128) NOT NULL REFERENCES edge_user(id) ON DELETE CASCADE,
 source_activity VARCHAR(36) NOT NULL REFERENCES activity(id) ON DELETE CASCADE,
 scoring_version VARCHAR(20) NOT NULL,summary TEXT NOT NULL,created_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
 UNIQUE(source_activity,scoring_version)
);
CREATE TABLE recommendation_dismissal(user_id VARCHAR(128) NOT NULL REFERENCES edge_user(id) ON DELETE CASCADE,rule_key VARCHAR(120) NOT NULL,until_at TIMESTAMP WITH TIME ZONE NOT NULL,PRIMARY KEY(user_id,rule_key));
CREATE TABLE audit_event(id VARCHAR(36) PRIMARY KEY,actor VARCHAR(128) NOT NULL,action VARCHAR(50) NOT NULL,target VARCHAR(128) NOT NULL,created_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP);

